### ISSUE TITLE
Titanic with both continuous and categorical data input

### ISSUE THREAD

**Issue by philbort** [ilblackdragon/tf_examples#7]
Can you add an example with using both continuous data (e.g., age and fare) and categorical data (e.g., class) as input for the tensorflow neural network implementation? I have been struggling with specifically how to set up "feature_columns" for it.

**Comment by ilblackdragon** [comment]
Indeed it's hard right now (we have some things in tensorflow pipeline to make it a lot easier), I'll try to add example in a few days.
If you have time before that - try doing something like this:
```
  le = LabelEncoder().fit(df['categorical_column'])
  df['categorical_column_ids'] = le.transform(df['categorical_column'])
```
and then define feature columns:
```
   feature_columns=[tf.contrib.layers.embedding_column('categorical_columns_ids', 10), ... other columns ...]
```

**Comment by philbort** [comment]
Will try. By the way, is the [Wide & Deep Learning](https://www.tensorflow.org/versions/r0.11/tutorials/wide_and_deep/index.html) the right model I should use?

**Comment by ilblackdragon** [comment]
You should try both LinearClassifier, DNNClassifier and DNNLinearCombined
(Wide&Deep) just to see what difference it makes to the final accuracy.
Usually Wide&Deep is good model as it combines both Linear and DNN, but you
still trading complexity - so you should know what you are buying.

**Comment by ilblackdragon** [comment]
Hm, apparently this is as easy as I though with feature columns, there is a bunch of pieces are still missing. Plus even reading dataframe properly requires an input function like this:
```
def pandas_input_fn(x, y=None, batch_size=128, num_epochs=None):
  if y is not None:
    x['target'] = y
  queue = learn.dataframe.queues.feeding_functions.enqueue_data(
    x, 1000, shuffle=num_epochs is None, num_epochs=num_epochs)
  if num_epochs is None:
    features = queue.dequeue_many(batch_size)
  else:
    features = queue.dequeue_up_to(batch_size)
  features = dict(zip(x.columns, features))
  if y is not None:
    target = features.pop('target')
    return features, target
  return features
```
I'll add a blog post how to get this all to work :)

**Comment by philbort** [comment]
Thanks, much appreciated.

**Comment by ilblackdragon** [comment]
Added an example https://github.com/ilblackdragon/tf_examples/blob/master/titanic_all_features.py  and posted more description in the blog - https://medium.com/@ilblackdragon/tensorflow-tutorial-part-4-958c29c717a0

**Comment by jinghuangzhu** [comment]
Hi, since now tensorflow r1.0 provides useful API functions such as read_batch_examples(), can you please update your script on how to use that for wide-and-deep tutorial? Because in that tutorial there are categorical features as well as continuous one, and there are sparseTensor input as well --- I read somewhere it says sparseTensor does not work well with queues. So an example script would be really help to deal with these cases. Thanks a lot.

**Comment by NitikaBhaskar** [comment]
Hi,  Could you please help with updating it for TensorFlow 1.0. I was trying to run my script (that work on TF 0.10). But, with TF 1.0, it fails with the following error:
 File "online_tensor1_Hotel.py", line 289, in <module>
    classifier.fit(input_fn=pandas_input_fn(X_train.loc[0:train_base,],y_train.loc[0:train_base]), steps=2500,monitors=[validation_monitor])
  File "/usr/lib/python2.7/dist-packages/tensorflow/python/util/deprecation.py", line 280, in new_func
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 426, in fit
    loss = self._train_model(input_fn=input_fn, hooks=hooks)
  File "/usr/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 932, in _train_model
    features, labels = input_fn()
  File "online_tensor1_Hotel.py", line 168, in input_fn
    queue = learn.DataFrame.queues.feeding_functions.enqueue_data(
AttributeError: 'module' object has no attribute 'DataFrame'

Would you have any suggestions?
